config/routes.rb
Rails.application.routes.draw do

  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def index
  @articles = Article.all
  end
  
def show
  @article = Article.find(params[:id])
  end

def new
  @article = Article.new
end

def create
  @article = Article.new(
  title: params[:article][:title],
  body: params[:article][:body])
  @article.save
  redirect_to article_path(@article)
end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title' %>
      <br>
      <%= link_to "Create a New Article YO", new_article_path, class: "new_article" %>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= form_for(@article) do |f| %>
   <ul>
   <% @article.errors.full_messages.each do |error| %>
   <li><%= error %></li>
   <% end %>
   </ul>
   <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
   </p>
   <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
    
    </p>
    <p>
     <%= f.submit %>
    </p>
   <% end %>

app/views/articles/show.html.erb
<h1><%  @article.title %></h1>
<p><%= @article.body %></p>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blagzo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>